usage: Apply this to any method that needs to be called with `User-Agent` header
description: Some requests require `User-Agent` header.
headers:
  User-Agent:
    description: Specifies the application (or service) that accesses to API.
    type: string
    required: true
    example: pacman-cli/0.0.1
