.PHONY: runserver runinspection

runserver:
	rm pacman || true
	go build && ./pacman server

runinspection:
	go tool vet .
	golint -min_confidence 0 ./...
	# errcheck ./...
	# defercheck ./...
	# structcheck -e ./...
	# varcheck -e ./...
