.PHONY: runserver runinspection

runserver:
	go run pman.go server

runinspection:
	go tool vet .
	golint -min_confidence 0 ./...
	# errcheck ./...
	# defercheck ./...
	# structcheck -e ./...
	# varcheck -e ./...
