.PHONY: runserver

runserver:
	gin --immediate run server

runinspection:
	go tool vet .
	golint -min_confidence 0 ./...
	# errcheck ./...
	# defercheck ./...
	# structcheck -e ./...
	# varcheck -e ./...
