# WARNING: Never ever modify this file

# Supported modes: release, debug and test
run_mode = "release"

[server]
port = "4242"

[db]
driver = "postgres"
spec = "user=pman dbname=pman sslmode=disable"
max_idle_conns = 10
max_open_conns = 100
log_mode = false
